sql_create.cc: allow update of NDMP Environment
Allow the update of NDMP Environment Values by handling errors like:

ERROR:  duplicate key value violates unique constraint "ndmpjobenvironment_pkey"
DETAIL:  Key (jobid, fileindex, envname)=(5, 1, HIST) already exists.